import { useEffect, useRef, useState, type ReactNode } from 'react'
import { api } from './api'
import type { Evidence, FindingCitation, Health, Run } from './types'
import { ExecutionMap, phases, statusNames, type MapNode } from './decision/ExecutionMap'
import { ResearchComposer } from './decision/ResearchComposer'
import { DetailPanel, SourceReader, type DetailTab } from './decision/DetailPanel'

function Modal({children,onClose,label}:{children:ReactNode;onClose:()=>void;label:string}){
 const ref=useRef<HTMLDivElement>(null),close=useRef(onClose);close.current=onClose
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const el=ref.current!;const first=el.querySelector<HTMLElement>('textarea[autofocus],input[autofocus],textarea,input')||el.querySelector<HTMLElement>('button,a');first?.focus();const listener=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();close.current()}if(e.key==='Tab'){const controls=Array.from(el.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),textarea:not(:disabled),summary')).filter(v=>v.getClientRects().length);const head=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===head){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();head?.focus()}}};el.addEventListener('keydown',listener);return()=>{el.removeEventListener('keydown',listener);previous?.focus()}},[])
 return <div className="dialog-backdrop"><div ref={ref} className="modal-shell" role="dialog" aria-modal="true" aria-label={label}>{children}</div></div>
}
export default function App(){
 const [health,setHealth]=useState<Health|null>(null),[history,setHistory]=useState<Run[]>([]),[run,setRun]=useState<Run|null>(null),[compose,setCompose]=useState(false),[historyOpen,setHistoryOpen]=useState(false),[selected,setSelected]=useState<MapNode|null>(null),[source,setSource]=useState<Evidence|null>(null),[citation,setCitation]=useState<FindingCitation|null>(null),[tab,setTab]=useState<DetailTab>('report'),[panelVisible,setPanelVisible]=useState(false),[error,setError]=useState(''),[filter,setFilter]=useState(''),[resuming,setResuming]=useState(false)
 useEffect(()=>{let live=true;Promise.all([api<Health>('/health'),api<Run[]>('/runs')]).then(([h,r])=>{if(live){setHealth(h);setHistory(r);setRun(r[0]||null)}}).catch(e=>{if(live)setError(e.message)});const timer=setInterval(()=>api<Health>('/health').then(h=>{if(live)setHealth(h)}).catch(()=>{}),15000);return()=>{live=false;clearInterval(timer)}},[])
 useEffect(()=>{setSelected(null);setSource(null);setTab(run?.forecast?'report':'event')},[run?.run_id])
 useEffect(()=>{if(!run||!['queued','running'].includes(run.status))return;let live=true;const id=run.run_id;const timer=setInterval(()=>{api<Run>(`/runs/${id}`).then(r=>{if(!live)return;setRun(r);if(!['queued','running'].includes(r.status)){setTab('report');api<Run[]>('/runs').then(setHistory)}}).catch(e=>{if(live)setError(e.message)})},1800);return()=>{live=false;clearInterval(timer)}},[run?.run_id,run?.status])
 async function created(id:string){try{setRun(await api<Run>(`/runs/${id}`));setHistory(await api<Run[]>('/runs'));setCompose(false);setSelected(null);setTab('event')}catch(e){setError((e as Error).message)}}
 async function resume(){if(!run)return;setResuming(true);setError('');try{await api(`/runs/${run.run_id}/resume`,{method:'POST'});setRun(await api<Run>(`/runs/${run.run_id}`))}catch(e){setError((e as Error).message)}finally{setResuming(false)}}
 const rounds=[...new Set((run?.simulation||[]).map(s=>s.round))]
 const stageCount=phases.filter(([k])=>run?.stage_outputs[k]).length
 const elapsed=run?(new Date(run.finished_at||Date.now()).getTime()-new Date(run.started_at).getTime())/1000:0
 const calls=[...new Map([...(run?.preparation_records||[]),...(run?.model_calls||[])].map(c=>[c.request_id,c])).values()].filter(c=>c.usage_known&&c.elapsed_seconds>0)
 const measuredSeconds=calls.reduce((s,c)=>s+c.elapsed_seconds,0),rate=measuredSeconds?calls.reduce((s,c)=>s+c.completion_tokens,0)/measuredSeconds:null
 const tokenTotal=(run?.usage.prompt_tokens||0)+(run?.usage.completion_tokens||0)
 function inspect(n:MapNode){setSelected(n);setPanelVisible(true);setTab(n.phase==='forecast'||n.phase==='review'?'report':n.phase==='world'||n.phase==='simulation'?'actors':'event')}
 function openReading(section:DetailTab){setTab(section);setSelected(null);setPanelVisible(true)}
 return <div className="forecast-app research-desk"><aside className="research-directory"><div className="desk-brand"><span>F/</span><div>ForecastLab<small>预测研究工作台</small></div></div><button className="directory-create" onClick={()=>setCompose(true)}>＋ 新建研究</button><nav className="directory-nav" aria-label="研究导航"><button className={!panelVisible?'active':''} onClick={()=>setPanelVisible(false)}><span>01</span>推演画布<small>探索路径</small></button><button className={panelVisible&&tab==='event'?'active':''} onClick={()=>openReading('event')}><span>02</span>问题与证据<small>{run?.evidence.length||0} 个来源</small></button><button className={panelVisible&&tab==='actors'?'active':''} onClick={()=>openReading('actors')}><span>03</span>主体与行动<small>{run?.world?.actors.length||0} 个主体</small></button><button className={panelVisible&&tab==='report'?'active':''} onClick={()=>openReading('report')}><span>04</span>研究报告<small>判断与边界</small></button></nav><div className="directory-history"><div><small>最近研究</small><button onClick={()=>setHistoryOpen(true)} aria-label="研究记录">全部 ↗</button></div>{history.slice(0,3).map(r=><button key={r.run_id} className={r.run_id===run?.run_id?'current':''} onClick={()=>{setRun(r);setSelected(null)}}><strong>{r.question.question}</strong><small>{new Date(r.started_at).toLocaleDateString('zh-CN')} · {statusNames[r.status]||r.status}</small></button>)}</div><div className="directory-services"><div><span className={health?.model_configured?'connection-dot':'connection-dot off'}/>{health?.model_configured?health.model:'模型未连接'}</div><div><span className={health?.search_configured?'connection-dot':'connection-dot off'}/>{health?.search_configured?'联网搜索可用':'搜索待配置'}</div><small title="已完成调用的输出 token 数除以请求耗时，包含输入处理">{rate===null?'等待首个调用':`${rate.toFixed(1)} 输出 token/s`}</small></div></aside><div className="desk-main"><header className="work-header"><div className="work-breadcrumb"><span>研究空间 / {!run?'未开始':run.demo?'教学回放':run.evidence_mode==='online'?'联网研究':'历史材料'}</span><button onClick={()=>setHistoryOpen(true)}>切换研究 ↗</button></div><h1>{run?.question.question||'把问题展开为可检查的路径'}</h1><div className="work-status"><span className={`status-label ${run?.status||''}`}>{run?statusNames[run.status]||run.status:'准备开始'}</span><span>{stageCount} / 6 阶段</span><div className="stage-progress" aria-label={`${stageCount}个阶段已完成`}>{phases.map(([id,label])=><i title={label} key={id} className={run?.stage_outputs[id]?'done':''}/>)}</div><span>{rounds.length} 轮演化</span><span>{Math.floor(Math.max(0,elapsed)/60)} 分 {Math.floor(Math.max(0,elapsed)%60)} 秒</span><span>{tokenTotal.toLocaleString()} tokens</span><button className="reading-toggle" onClick={()=>setPanelVisible(v=>!v)} aria-label={panelVisible?'收起详情面板':'展开详情面板'}>{panelVisible?'收起阅读区 ↑':'展开阅读区 ↓'}</button></div></header>
 {run?.forecast&&<div className="outcome-brief"><span>当前判断</span><strong>{run.forecast.conclusion}</strong><button onClick={()=>openReading('report')}>依据与限制 ↗</button></div>}
 {error&&<div role="alert" className="app-alert"><span>{error}</span><button aria-label="关闭错误提示" onClick={()=>setError('')}>×</button></div>}
 <main className={`research-space ${panelVisible?'panel-open':''}`}><div className="canvas-area"><ExecutionMap run={run} onInspect={inspect} selectedId={selected?.id}/>{!run&&<div className="first-research"><small>开始一项研究</small><h2>提出问题，检查依据，探索可能的未来。</h2><p>每个节点连接一次真实的分析、取证或推演记录。</p><button className="primary" onClick={()=>setCompose(true)}>新建事件研究 →</button></div>}</div>
 {panelVisible&&<DetailPanel run={run} tab={tab} node={selected} onClose={()=>setPanelVisible(false)} onClear={()=>setSelected(null)} onSource={e=>{setCitation(null);setSource(e)}} onCitation={c=>{const e=run?.evidence.find(e=>e.id===c.evidence_id);if(e){setCitation(c);setSource(e)}}} onNew={()=>setCompose(true)}/>}</main>
 {run&&['failed','interrupted','partial'].includes(run.status)&&<div className="resume-line"><span>运行在 {run.failed_stage||run.stage} 阶段中断</span><button disabled={resuming} onClick={resume}>从失败阶段继续 ↗</button></div>}
 </div>
  {compose&&<Modal label="新建事件研究" onClose={()=>setCompose(false)}><ResearchComposer searchReady={!!health?.search_configured} onClose={()=>setCompose(false)} onCreated={created}/></Modal>}
  {source&&run&&<Modal label="来源原文" onClose={()=>setSource(null)}><SourceReader run={run} evidence={source} citation={citation} onClose={()=>setSource(null)}/></Modal>}
  {historyOpen&&<Modal label="研究记录" onClose={()=>setHistoryOpen(false)}><section className="history-dialog"><header><div><small>RESEARCH HISTORY</small><h2>每一次判断，都有一条路径</h2></div><button aria-label="关闭研究记录" onClick={()=>setHistoryOpen(false)}>×</button></header><div className="dialog-body"><label className="input-field"><span>筛选研究记录</span><input placeholder="搜索事件或研究问题" value={filter} onChange={e=>setFilter(e.target.value)}/></label>{history.filter(r=>r.question.question.includes(filter)).map(r=><button className="history-row" key={r.run_id} onClick={()=>{setRun(r);setHistoryOpen(false);setSelected(null)}}><strong>{r.question.question}</strong><div><span>{statusNames[r.status]||r.status}</span><small>{new Date(r.started_at).toLocaleString('zh-CN')} · {r.model} · {r.demo?'固定教学':r.evidence_mode==='online'?'联网取证':'历史测试'}</small></div></button>)}{!history.length&&<p className="subtle">尚无研究记录。新建一个事件，开始第一条路径。</p>}</div></section></Modal>}
 </div>
}
